## Pandas

Pandas is an open-source Python Library providing high-performance data manipulation and analysis tool using its powerful data structures. The name Pandas is derived from the word Panel Data – an Econometrics from Multidimensional data.


If you install Anaconda Python package, Pandas will be installed by default.

A helful website with tutorials: https://www.tutorialspoint.com/python_pandas/index.htm

Pandas deals with the following three data structures:

- Series: 1D

- DataFrame:  2D

- Panel: 3D

Pandas DataFrame is two-dimensional size-mutable, tabular data structure with labeled axes (rows and columns).

In [1]:
import numpy as np
import pandas as pd



### Missing values

In [2]:
# add missing value with np.nan
#columns=dimension, feature, attribute


df=pd.DataFrame([[1.5,2.5,np.nan,"blue"],
               [10,np.nan,1000,"red"],
               [np.nan,np.nan,np.nan,np.nan],
               [2,0,4,"red"],
               [40,40,40,"blue"],
               [1,2,3,np.nan]], columns=["f1","f2","f3","f4"] )

In [86]:
df

#f4 categorical

f1    f2      f3    f4
0   1.5   2.5     NaN  blue
1  10.0   NaN  1000.0   red
2   NaN   NaN     NaN   NaN
3   2.0   0.0     4.0   red
4  40.0  40.0    40.0  blue
5   1.0   2.0     3.0   NaN

In [87]:
df["f1"] #index

0     1.5
1    10.0
2     NaN
3     2.0
4    40.0
5     1.0
Name: f1, dtype: float64

In [88]:
df.f4

0    blue
1     red
2     NaN
3     red
4    blue
5     NaN
Name: f4, dtype: object

In [89]:
df.f4.

SyntaxError: invalid syntax (<ipython-input-89-1922498897ac>, line 1)

In [90]:
df.f4.value_counts()   #unique values        press tab.  tutorials documentation
#generally learn about features experience projects 

red     2
blue    2
Name: f4, dtype: int64

In [91]:
df.isnull() #which is missing True/False

f1     f2     f3     f4
0  False  False   True  False
1  False   True  False  False
2   True   True   True   True
3  False  False  False  False
4  False  False  False  False
5  False  False  False   True

In [92]:
df.isnull().sum()# how many missing values 

f1    1
f2    2
f3    2
f4    2
dtype: int64

In [93]:
df.isnull().mean()# perc of missing of feature

f1    0.166667
f2    0.333333
f3    0.333333
f4    0.333333
dtype: float64

In [94]:
 
df.isna()  #identical to .isnull()

f1     f2     f3     f4
0  False  False   True  False
1  False   True  False  False
2   True   True   True   True
3  False  False  False  False
4  False  False  False  False
5  False  False  False   True

In [95]:
 
pd.isna(df["f1"])   

0    False
1    False
2     True
3    False
4    False
5    False
Name: f1, dtype: bool

In [96]:
 
pd.isnull(df["f1"])

0    False
1    False
2     True
3    False
4    False
5    False
Name: f1, dtype: bool

#### impute

In [97]:

df.fillna(-1)   

f1    f2      f3    f4
0   1.5   2.5    -1.0  blue
1  10.0  -1.0  1000.0   red
2  -1.0  -1.0    -1.0    -1
3   2.0   0.0     4.0   red
4  40.0  40.0    40.0  blue
5   1.0   2.0     3.0    -1

In [98]:
df

f1    f2      f3    f4
0   1.5   2.5     NaN  blue
1  10.0   NaN  1000.0   red
2   NaN   NaN     NaN   NaN
3   2.0   0.0     4.0   red
4  40.0  40.0    40.0  blue
5   1.0   2.0     3.0   NaN

In [99]:
 
df.mean()
#automatically discards the missing values before calculating the mean  
#we don't get notified even if 90% nan so not representative

f1     10.900
f2     11.125
f3    261.750
dtype: float64

In [100]:
 
df.fillna(df.mean())   #impute missing with mean of existing   #categorical feature no

f1      f2       f3    f4
0   1.5   2.500   261.75  blue
1  10.0  11.125  1000.00   red
2  10.9  11.125   261.75   NaN
3   2.0   0.000     4.00   red
4  40.0  40.000    40.00  blue
5   1.0   2.000     3.00   NaN

In [101]:
 
df.fillna(df.mean()["f1":"f2"])  #restrict imputing to only two columns

f1      f2      f3    f4
0   1.5   2.500     NaN  blue
1  10.0  11.125  1000.0   red
2  10.9  11.125     NaN   NaN
3   2.0   0.000     4.0   red
4  40.0  40.000    40.0  blue
5   1.0   2.000     3.0   NaN

In [102]:
 
df.fillna(value={"f1":-1 , "f2":-2, "f3":-3, "f4":"purple"})  #impute manually

f1    f2      f3      f4
0   1.5   2.5    -3.0    blue
1  10.0  -2.0  1000.0     red
2  -1.0  -2.0    -3.0  purple
3   2.0   0.0     4.0     red
4  40.0  40.0    40.0    blue
5   1.0   2.0     3.0  purple

In [103]:
df

f1    f2      f3    f4
0   1.5   2.5     NaN  blue
1  10.0   NaN  1000.0   red
2   NaN   NaN     NaN   NaN
3   2.0   0.0     4.0   red
4  40.0  40.0    40.0  blue
5   1.0   2.0     3.0   NaN

In [104]:
 
df.fillna(method="ffill")   
#replaces with the last existing value (longitudinal, continuity)

f1    f2      f3    f4
0   1.5   2.5     NaN  blue
1  10.0   2.5  1000.0   red
2  10.0   2.5  1000.0   red
3   2.0   0.0     4.0   red
4  40.0  40.0    40.0  blue
5   1.0   2.0     3.0  blue

#### omit

In [105]:

df.dropna()   #omit missing.  now you have a complete dataset at the cost of losing info

f1    f2    f3    f4
3   2.0   0.0   4.0   red
4  40.0  40.0  40.0  blue

In [106]:
df["f1"].dropna()

0     1.5
1    10.0
3     2.0
4    40.0
5     1.0
Name: f1, dtype: float64

In [116]:
df.dropna(subset=["f2"]) 

f1    f2    f3    f4
0   1.5   2.5   NaN  blue
3   2.0   0.0   4.0   red
4  40.0  40.0  40.0  blue
5   1.0   2.0   3.0   NaN

In [107]:
df.dropna(how='all')  #only omit those with all features missing

f1    f2      f3    f4
0   1.5   2.5     NaN  blue
1  10.0   NaN  1000.0   red
3   2.0   0.0     4.0   red
4  40.0  40.0    40.0  blue
5   1.0   2.0     3.0   NaN

In [110]:
df.dropna(thresh=2)  #keep rows with at least 2 existing features

f1    f2      f3    f4
0   1.5   2.5     NaN  blue
1  10.0   NaN  1000.0   red
3   2.0   0.0     4.0   red
4  40.0  40.0    40.0  blue
5   1.0   2.0     3.0   NaN

#### groupby

In [111]:

D=pd.DataFrame({"Sports":["B","B","B","T","T","T"],"Height":[204,211,198,175,172,np.nan]})
D

Sports  Height
0      B   204.0
1      B   211.0
2      B   198.0
3      T   175.0
4      T   172.0
5      T     NaN

In [112]:
D.groupby(["Sports"]).mean()  #use this information to impute better

Height
Sports            
B       204.333333
T       173.500000

In [113]:
D["Height"]=D.groupby(["Sports"])["Height"].transform(lambda x: x.fillna(x.mean()))
D

Sports  Height
0      B   204.0
1      B   211.0
2      B   198.0
3      T   175.0
4      T   172.0
5      T   173.5

### Feature selection

In [119]:
df

f1    f2      f3    f4
0   1.5   2.5     NaN  blue
1  10.0   NaN  1000.0   red
2   NaN   NaN     NaN   NaN
3   2.0   0.0     4.0   red
4  40.0  40.0    40.0  blue
5   1.0   2.0     3.0   NaN

In [120]:
df.drop("f4",axis=1)

f1    f2      f3
0   1.5   2.5     NaN
1  10.0   NaN  1000.0
2   NaN   NaN     NaN
3   2.0   0.0     4.0
4  40.0  40.0    40.0
5   1.0   2.0     3.0

In [3]:
df2=df.drop(["f2","f4"],axis=1)
df2

f1      f3
0   1.5     NaN
1  10.0  1000.0
2   NaN     NaN
3   2.0     4.0
4  40.0    40.0
5   1.0     3.0

In [122]:
df

f1    f2      f3    f4
0   1.5   2.5     NaN  blue
1  10.0   NaN  1000.0   red
2   NaN   NaN     NaN   NaN
3   2.0   0.0     4.0   red
4  40.0  40.0    40.0  blue
5   1.0   2.0     3.0   NaN

### sampling

In [124]:

df2=df.drop([0,1,4],axis=0)

In [125]:
df2

f1   f2   f3   f4
2  NaN  NaN  NaN  NaN
3  2.0  0.0  4.0  red
5  1.0  2.0  3.0  NaN

#### (one hot encoding)

categorical data encoded as dummy variable (indicator valriable) only two colors instaed of strings two columns with binary. 3 color 3 columns 

In [126]:
df3=pd.get_dummies(df)
df3

f1    f2      f3  f4_blue  f4_red
0   1.5   2.5     NaN        1       0
1  10.0   NaN  1000.0        0       1
2   NaN   NaN     NaN        0       0
3   2.0   0.0     4.0        0       1
4  40.0  40.0    40.0        1       0
5   1.0   2.0     3.0        0       0

In [127]:
df

f1    f2      f3    f4
0   1.5   2.5     NaN  blue
1  10.0   NaN  1000.0   red
2   NaN   NaN     NaN   NaN
3   2.0   0.0     4.0   red
4  40.0  40.0    40.0  blue
5   1.0   2.0     3.0   NaN

In [ ]:
#missing values 0 0 

### Scikit-learn

Scikit-learn (Sklearn) is a useful and robust library for machine learning in Python. It provides a selection of efficient tools for **machine learning and statistical modeling** including **classification, regression, clustering and dimensionality reduction** via a consistence interface in Python. 

Useful tutorials found at https://www.tutorialspoint.com/scikit_learn/index.htm

If you install Anaconda Python package, Scikit-learn will be installed by default.

In [23]:
from sklearn import preprocessing
from sklearn.impute import SimpleImputer

In [26]:
imr=SimpleImputer(missing_values=np.nan,strategy="mean")   #impute with mean

In [25]:
imr=imr.fit(df2)   #only numerical columns for mean

In [16]:
imputed_df=imr.transform(df2.values)

In [17]:
imputed_df  #np.array

array([[   1.5 ,  261.75],
       [  10.  , 1000.  ],
       [  10.9 ,  261.75],
       [   2.  ,    4.  ],
       [  40.  ,   40.  ],
       [   1.  ,    3.  ]])

In [31]:
imputed_df[:]=imr.fit_transform(df2.values)  #or combine in one step

In [32]:
imputed_df

array([[   1.5 ,  261.75],
       [  10.  , 1000.  ],
       [  10.9 ,  261.75],
       [   2.  ,    4.  ],
       [  40.  ,   40.  ],
       [   1.  ,    3.  ]])

In [33]:
df2

f1      f3
0   1.5     NaN
1  10.0  1000.0
2   NaN     NaN
3   2.0     4.0
4  40.0    40.0
5   1.0     3.0

### Data Transformation

In [34]:
from sklearn.preprocessing import MinMaxScaler

#### min-max normalization

In [35]:
ourData=[[10,10,10],[20,12,30],[30,20,70]]
ourData

[[10, 10, 10], [20, 12, 30], [30, 20, 70]]

In [36]:
scaler=MinMaxScaler()   #default axis=0 so the normalization occurs across columns
scaler.fit_transform(ourData)

array([[0.        , 0.        , 0.        ],
       [0.5       , 0.2       , 0.33333333],
       [1.        , 1.        , 1.        ]])

#### standarziation: z-score 

In [37]:
from sklearn.preprocessing import StandardScaler


In [38]:
scaler=StandardScaler()
sc=scaler.fit_transform(ourData)
sc

array([[-1.22474487, -0.9258201 , -1.06904497],
       [ 0.        , -0.46291005, -0.26726124],
       [ 1.22474487,  1.38873015,  1.33630621]])

In [39]:
sc.mean(axis=0)   #the new data points have mean 0 and sd=1

array([0.00000000e+00, 0.00000000e+00, 7.40148683e-17])

In [40]:
sc.std(axis=0)

array([1., 1., 1.])

### Titanic dataset

In [41]:
df=pd.read_csv("titanic.csv")

In [42]:
df.info()  #summary

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 891 entries, 0 to 890
Data columns (total 12 columns):
 #   Column       Non-Null Count  Dtype  
---  ------       --------------  -----  
 0   PassengerId  891 non-null    int64  
 1   Survived     891 non-null    int64  
 2   Pclass       891 non-null    int64  
 3   Name         891 non-null    object 
 4   Sex          891 non-null    object 
 5   Age          714 non-null    float64
 6   SibSp        891 non-null    int64  
 7   Parch        891 non-null    int64  
 8   Ticket       891 non-null    object 
 9   Fare         891 non-null    float64
 10  Cabin        204 non-null    object 
 11  Embarked     889 non-null    object 
dtypes: float64(2), int64(5), object(5)
memory usage: 83.7+ KB


In [43]:
df

PassengerId  Survived  Pclass  \
0              1         0       3   
1              2         1       1   
2              3         1       3   
3              4         1       1   
4              5         0       3   
..           ...       ...     ...   
886          887         0       2   
887          888         1       1   
888          889         0       3   
889          890         1       1   
890          891         0       3   

                                                  Name     Sex   Age  SibSp  \
0                              Braund, Mr. Owen Harris    male  22.0      1   
1    Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                               Heikkinen, Miss. Laina  female  26.0      0   
3         Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                             Allen, Mr. William Henry    male  35.0      0   
..                                                 ...     ...   ...    ...   
886                              Montvila, Rev. Juozas    male  27.0      0   
887                       Graham, Miss. Margaret Edith  female  19.0      0   
888           Johnston, Miss. Catherine Helen "Carrie"  female   NaN      1   
889                              Behr, Mr. Karl Howell    male  26.0      0   
890                                Dooley, Mr. Patrick    male  32.0      0   

     Parch            Ticket     Fare Cabin Embarked  
0        0         A/5 21171   7.2500   NaN        S  
1        0          PC 17599  71.2833   C85        C  
2        0  STON/O2. 3101282   7.9250   NaN        S  
3        0            113803  53.1000  C123        S  
4        0            373450   8.0500   NaN        S  
..     ...               ...      ...   ...      ...  
886      0            211536  13.0000   NaN        S  
887      0            112053  30.0000   B42        S  
888      2        W./C. 6607  23.4500   NaN        S  
889      0            111369  30.0000  C148        C  
890      0            370376   7.7500   NaN        Q  

[891 rows x 12 columns]

In [44]:
df.head()

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S

In [45]:
df.head(9)

PassengerId  Survived  Pclass  \
0            1         0       3   
1            2         1       1   
2            3         1       3   
3            4         1       1   
4            5         0       3   
5            6         0       3   
6            7         0       1   
7            8         0       3   
8            9         1       3   

                                                Name     Sex   Age  SibSp  \
0                            Braund, Mr. Owen Harris    male  22.0      1   
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  female  38.0      1   
2                             Heikkinen, Miss. Laina  female  26.0      0   
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  female  35.0      1   
4                           Allen, Mr. William Henry    male  35.0      0   
5                                   Moran, Mr. James    male   NaN      0   
6                            McCarthy, Mr. Timothy J    male  54.0      0   
7                     Palsson, Master. Gosta Leonard    male   2.0      3   
8  Johnson, Mrs. Oscar W (Elisabeth Vilhelmina Berg)  female  27.0      0   

   Parch            Ticket     Fare Cabin Embarked  
0      0         A/5 21171   7.2500   NaN        S  
1      0          PC 17599  71.2833   C85        C  
2      0  STON/O2. 3101282   7.9250   NaN        S  
3      0            113803  53.1000  C123        S  
4      0            373450   8.0500   NaN        S  
5      0            330877   8.4583   NaN        Q  
6      0             17463  51.8625   E46        S  
7      1            349909  21.0750   NaN        S  
8      2            347742  11.1333   NaN        S

In [46]:
df.shape  #size

(891, 12)

In [47]:
df.describe()  #summary statistics for numerical features

PassengerId    Survived      Pclass         Age       SibSp  \
count   891.000000  891.000000  891.000000  714.000000  891.000000   
mean    446.000000    0.383838    2.308642   29.699118    0.523008   
std     257.353842    0.486592    0.836071   14.526497    1.102743   
min       1.000000    0.000000    1.000000    0.420000    0.000000   
25%     223.500000    0.000000    2.000000   20.125000    0.000000   
50%     446.000000    0.000000    3.000000   28.000000    0.000000   
75%     668.500000    1.000000    3.000000   38.000000    1.000000   
max     891.000000    1.000000    3.000000   80.000000    8.000000   

            Parch        Fare  
count  891.000000  891.000000  
mean     0.381594   32.204208  
std      0.806057   49.693429  
min      0.000000    0.000000  
25%      0.000000    7.910400  
50%      0.000000   14.454200  
75%      0.000000   31.000000  
max      6.000000  512.329200

In [50]:
#feature selection, removing the features not releveant to our analyisis 

df=df.drop(["PassengerId","Name","Ticket"],axis=1)  



In [51]:
df.isna()

Survived  Pclass    Sex    Age  SibSp  Parch   Fare  Cabin  Embarked
0       False   False  False  False  False  False  False   True     False
1       False   False  False  False  False  False  False  False     False
2       False   False  False  False  False  False  False   True     False
3       False   False  False  False  False  False  False  False     False
4       False   False  False  False  False  False  False   True     False
..        ...     ...    ...    ...    ...    ...    ...    ...       ...
886     False   False  False  False  False  False  False   True     False
887     False   False  False  False  False  False  False  False     False
888     False   False  False   True  False  False  False   True     False
889     False   False  False  False  False  False  False  False     False
890     False   False  False  False  False  False  False   True     False

[891 rows x 9 columns]

In [52]:
no_ports = df[df["Embarked"].isna()]
no_ports

Survived  Pclass     Sex   Age  SibSp  Parch  Fare Cabin Embarked
61          1       1  female  38.0      0      0  80.0   B28      NaN
829         1       1  female  62.0      0      0  80.0   B28      NaN

In [53]:
df[df["Age"].isna()]

Survived  Pclass     Sex  Age  SibSp  Parch     Fare Cabin Embarked
5           0       3    male  NaN      0      0   8.4583   NaN        Q
17          1       2    male  NaN      0      0  13.0000   NaN        S
19          1       3  female  NaN      0      0   7.2250   NaN        C
26          0       3    male  NaN      0      0   7.2250   NaN        C
28          1       3  female  NaN      0      0   7.8792   NaN        Q
..        ...     ...     ...  ...    ...    ...      ...   ...      ...
859         0       3    male  NaN      0      0   7.2292   NaN        C
863         0       3  female  NaN      8      2  69.5500   NaN        S
868         0       3    male  NaN      0      0   9.5000   NaN        S
878         0       3    male  NaN      0      0   7.8958   NaN        S
888         0       3  female  NaN      1      2  23.4500   NaN        S

[177 rows x 9 columns]

In [54]:
df[df["Age"].isna()].groupby("Sex").size() #categorize the data based on categorical feature

Sex
female     53
male      124
dtype: int64

In [ ]:
#more missing data on age for male. any imbalnaces?

In [55]:
df.groupby("Sex").size()

Sex
female    314
male      577
dtype: int64

In [56]:
53/314,124/577

(0.16878980891719744, 0.21490467937608318)

In [ ]:
df

In [57]:
dum=pd.get_dummies(df["Embarked"])  #best for many python packages
dum

C  Q  S
0    0  0  1
1    1  0  0
2    0  0  1
3    0  0  1
4    0  0  1
..  .. .. ..
886  0  0  1
887  0  0  1
888  0  0  1
889  1  0  0
890  0  1  0

[891 rows x 3 columns]

In [58]:
df=df.join(dum) #join the dummies to the df

In [59]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin Embarked  C  \
0           0       3    male  22.0      1      0   7.2500   NaN        S  0   
1           1       1  female  38.0      1      0  71.2833   C85        C  1   
2           1       3  female  26.0      0      0   7.9250   NaN        S  0   
3           1       1  female  35.0      1      0  53.1000  C123        S  0   
4           0       3    male  35.0      0      0   8.0500   NaN        S  0   
..        ...     ...     ...   ...    ...    ...      ...   ...      ... ..   
886         0       2    male  27.0      0      0  13.0000   NaN        S  0   
887         1       1  female  19.0      0      0  30.0000   B42        S  0   
888         0       3  female   NaN      1      2  23.4500   NaN        S  0   
889         1       1    male  26.0      0      0  30.0000  C148        C  1   
890         0       3    male  32.0      0      0   7.7500   NaN        Q  0   

     Q  S  
0    0  1  
1    0  0  
2    0  1  
3    0  1  
4    0  1  
..  .. ..  
886  0  1  
887  0  1  
888  0  1  
889  0  0  
890  1  0  

[891 rows x 12 columns]

In [60]:
#we can now remove embraked
df.drop(["Embarked"],axis=1,inplace=True)

In [61]:
df

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin  C  Q  S
0           0       3    male  22.0      1      0   7.2500   NaN  0  0  1
1           1       1  female  38.0      1      0  71.2833   C85  1  0  0
2           1       3  female  26.0      0      0   7.9250   NaN  0  0  1
3           1       1  female  35.0      1      0  53.1000  C123  0  0  1
4           0       3    male  35.0      0      0   8.0500   NaN  0  0  1
..        ...     ...     ...   ...    ...    ...      ...   ... .. .. ..
886         0       2    male  27.0      0      0  13.0000   NaN  0  0  1
887         1       1  female  19.0      0      0  30.0000   B42  0  0  1
888         0       3  female   NaN      1      2  23.4500   NaN  0  0  1
889         1       1    male  26.0      0      0  30.0000  C148  1  0  0
890         0       3    male  32.0      0      0   7.7500   NaN  0  1  0

[891 rows x 11 columns]

In [62]:
df[    (df["Age"] > 0) & (df["Age"] < 10.0 )     ]  #subset  #automatically removes nan

Survived  Pclass     Sex   Age  SibSp  Parch     Fare Cabin  C  Q  S
7           0       3    male  2.00      3      1  21.0750   NaN  0  0  1
10          1       3  female  4.00      1      1  16.7000    G6  0  0  1
16          0       3    male  2.00      4      1  29.1250   NaN  0  1  0
24          0       3  female  8.00      3      1  21.0750   NaN  0  0  1
43          1       2  female  3.00      1      2  41.5792   NaN  1  0  0
..        ...     ...     ...   ...    ...    ...      ...   ... .. .. ..
827         1       2    male  1.00      0      2  37.0042   NaN  1  0  0
831         1       2    male  0.83      1      1  18.7500   NaN  0  0  1
850         0       3    male  4.00      4      2  31.2750   NaN  0  0  1
852         0       3  female  9.00      1      1  15.2458   NaN  1  0  0
869         1       3    male  4.00      1      1  11.1333   NaN  0  0  1

[62 rows x 11 columns]

In [65]:
df2=df.sample(n=100)   #uniform sampling based on random generators  #new df

In [66]:
df2

Survived  Pclass     Sex   Age  SibSp  Parch      Fare    Cabin  C  Q  S
129         0       3    male  45.0      0      0    6.9750      NaN  0  0  1
390         1       1    male  36.0      1      2  120.0000  B96 B98  0  0  1
501         0       3  female  21.0      0      0    7.7500      NaN  0  1  0
579         1       3    male  32.0      0      0    7.9250      NaN  0  0  1
677         1       3  female  18.0      0      0    9.8417      NaN  0  0  1
..        ...     ...     ...   ...    ...    ...       ...      ... .. .. ..
359         1       3  female   NaN      0      0    7.8792      NaN  0  1  0
733         0       2    male  23.0      0      0   13.0000      NaN  0  0  1
122         0       2    male  32.5      1      0   30.0708      NaN  1  0  0
573         1       3  female   NaN      0      0    7.7500      NaN  0  1  0
300         1       3  female   NaN      0      0    7.7500      NaN  0  1  0

[100 rows x 11 columns]

In [67]:
df.sample(frac=0.01)

Survived  Pclass     Sex   Age  SibSp  Parch      Fare Cabin  C  Q  S
737         1       1    male  35.0      0      0  512.3292  B101  1  0  0
889         1       1    male  26.0      0      0   30.0000  C148  1  0  0
515         0       1    male  47.0      0      0   34.0208   D46  0  0  1
887         1       1  female  19.0      0      0   30.0000   B42  0  0  1
46          0       3    male   NaN      1      0   15.5000   NaN  0  1  0
82          1       3  female   NaN      0      0    7.7875   NaN  0  1  0
598         0       3    male   NaN      0      0    7.2250   NaN  1  0  0
867         0       1    male  31.0      0      0   50.4958   A24  0  0  1
878         0       3    male   NaN      0      0    7.8958   NaN  0  0  1

In [68]:
df["Cabin"].str.contains("C")   #search for rows with C

0        NaN
1       True
2        NaN
3       True
4        NaN
       ...  
886      NaN
887    False
888      NaN
889     True
890      NaN
Name: Cabin, Length: 891, dtype: object

In [69]:
df["Cabin"].str.contains("C",na=False)  #for nan put false

0      False
1       True
2      False
3       True
4      False
       ...  
886    False
887    False
888    False
889     True
890    False
Name: Cabin, Length: 891, dtype: bool

In [70]:
df["Cabin"].str.contains("C",na=False).sum()  

59

In [71]:
df.groupby(["Sex"]).size() 

Sex
female    314
male      577
dtype: int64

In [72]:
df.groupby("Sex").Fare.mean()

Sex
female    44.479818
male      25.523893
Name: Fare, dtype: float64

In [73]:
df.groupby("Sex").Survived.mean()

Sex
female    0.742038
male      0.188908
Name: Survived, dtype: float64

#### Cross Tab
good for statistical tests like chi-sqaure

In [74]:
t = pd.crosstab(df["Survived"],df["Sex"])
t  

Sex       female  male
Survived              
0             81   468
1            233   109

In [75]:
df.groupby("Pclass").Fare.mean()
# or df.groupby("Pclass")["Fare"].mean()

Pclass
1    84.154687
2    20.662183
3    13.675550
Name: Fare, dtype: float64

In [76]:
 #first divide based on pclass then based on sex
fare_plass_sex= df.groupby(["Pclass","Sex"])["Fare"].mean() 
fare_plass_sex   

Pclass  Sex   
1       female    106.125798
        male       67.226127
2       female     21.970121
        male       19.741782
3       female     16.118810
        male       12.661633
Name: Fare, dtype: float64

In [77]:
fare_plass_sex= df.groupby(["Sex","Pclass"])["Fare"].mean() 
fare_plass_sex   

Sex     Pclass
female  1         106.125798
        2          21.970121
        3          16.118810
male    1          67.226127
        2          19.741782
        3          12.661633
Name: Fare, dtype: float64

In [78]:
df.groupby("Pclass").Survived.mean()

Pclass
1    0.629630
2    0.472826
3    0.242363
Name: Survived, dtype: float64

In [79]:
df.groupby(["Pclass","Sex"]).Survived.mean()

Pclass  Sex   
1       female    0.968085
        male      0.368852
2       female    0.921053
        male      0.157407
3       female    0.500000
        male      0.135447
Name: Survived, dtype: float64

In [80]:
#repeat the analysis for children

df[df["Age"]<10].groupby(["Pclass","Sex"]).size()  

Pclass  Sex   
1       female     1
        male       2
2       female     8
        male       9
3       female    21
        male      21
dtype: int64

In [81]:
df[df["Age"]<10].groupby(["Pclass","Sex"]).Survived.mean()

Pclass  Sex   
1       female    0.000000
        male      1.000000
2       female    1.000000
        male      1.000000
3       female    0.523810
        male      0.380952
Name: Survived, dtype: float64

In [82]:
t = pd.crosstab(df["Survived"],df["Pclass"])
t

Pclass      1   2    3
Survived              
0          80  97  372
1         136  87  119

In [83]:
max_fare=df["Fare"].max()  #the max value
df[    df["Fare"]==max_fare    ]  #find the row(s) with max value

Survived  Pclass     Sex   Age  SibSp  Parch      Fare        Cabin  C  \
258         1       1  female  35.0      0      0  512.3292          NaN  1   
679         1       1    male  36.0      0      1  512.3292  B51 B53 B55  1   
737         1       1    male  35.0      0      0  512.3292         B101  1   

     Q  S  
258  0  0  
679  0  0  
737  0  0